Feature: Compare Files
  I want to compare the files generated by Authentic ATM to be sure that the information is  correct

  Background:
    Given Authentic ATM generated the files

  Scenario: Compare ATM Files
    When Cesar compares the reference information with the ATM information
    Then Cesar should see the information is correct